// <auto-generated />
using System;
using Giydir.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Giydir.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213133802_AddAiGeneratedModelSeed")]
    partial class AddAiGeneratedModelSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Giydir.Core.Entities.GeneratedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalClothingPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplicatePredictionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelAssetId");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeneratedImages");
                });

            modelBuilder.Entity("Giydir.Core.Entities.ModelAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBackground")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCameraAngle")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLighting")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMood")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPose")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelAssets");

                    b.HasData(
                        new
                        {
                            Id = "elena-s",
                            Category = "Studio / Casual",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuBi-JZTVchJ7MDg0T4cmwa7gac-HLXK1ubWKFs8d0CEzRbuEmZZBjol8-E2_0nynXHYYBWDZ18Da81JWBgzL89oRYxxHoYGkK_X_AoUBzPPRH1fslzv_CZSzHHTl0eEdiYwPIr4_AJiVF1qbkcS1uoc7QnPlQkV5ikxMhCWx1wDDIkT5-VmuVgKMv9RHtygmjMP614JOHRWUhXlz7WzCkzxdz5w5eP6nYau5gbOaSYsMgGV2GvNwU-0IBuCF6NxHBZfyP3UQ7Ye9WoD",
                            Gender = "Female",
                            Name = "Elena S.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuBi-JZTVchJ7MDg0T4cmwa7gac-HLXK1ubWKFs8d0CEzRbuEmZZBjol8-E2_0nynXHYYBWDZ18Da81JWBgzL89oRYxxHoYGkK_X_AoUBzPPRH1fslzv_CZSzHHTl0eEdiYwPIr4_AJiVF1qbkcS1uoc7QnPlQkV5ikxMhCWx1wDDIkT5-VmuVgKMv9RHtygmjMP614JOHRWUhXlz7WzCkzxdz5w5eP6nYau5gbOaSYsMgGV2GvNwU-0IBuCF6NxHBZfyP3UQ7Ye9WoD"
                        },
                        new
                        {
                            Id = "marcus-j",
                            Category = "Street / Urban",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuAeXc4bOfxLbkVLRqH-4051XnkJqMoSi0DqAgiEV1SsI0sdvwv_Vq3P3CRl7TmzS0RblYW6cVn7yQQxbmBCBEuGDpuKls8IMwDOiQo0RbN7xbcGOar_N58kqg8ih0NbaTh3LNFH8KuFBQDlyTOTay1LGiKtPWzuf_bWF_Zop6TfzYxylk0XYPoqXXRzwPWOjK0z99e0gGuefuSmMSvCUCRtR59cBKKfeE-dlDe9ghuirK4cNa25d3llmDNFhipCxav3Sb5ZV8LoSI-E",
                            Gender = "Male",
                            Name = "Marcus J.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuAeXc4bOfxLbkVLRqH-4051XnkJqMoSi0DqAgiEV1SsI0sdvwv_Vq3P3CRl7TmzS0RblYW6cVn7yQQxbmBCBEuGDpuKls8IMwDOiQo0RbN7xbcGOar_N58kqg8ih0NbaTh3LNFH8KuFBQDlyTOTay1LGiKtPWzuf_bWF_Zop6TfzYxylk0XYPoqXXRzwPWOjK0z99e0gGuefuSmMSvCUCRtR59cBKKfeE-dlDe9ghuirK4cNa25d3llmDNFhipCxav3Sb5ZV8LoSI-E"
                        },
                        new
                        {
                            Id = "sophia-l",
                            Category = "Outdoor / Lifestyle",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuAlm9ZnHv3XtmLsmCiE3BVixApLiZMOQQdxDL5p5s8XuWtINXFvePRxvb8cUJSMjPewgmI7KxhhZ4HDO05TkDeLrkXzZwDHElUSf-2Z3iqpnnGoW3cfdX8p-6rKBtb-iu8gMVI3-Xcauke-Ro6DNyQ7KtS6P84UoaY_Zrww-vicwSjDHtld1Z2SlPGVz7flzgID5kTv33hkULsiw7lwA4A6iRoZXLhlGcw_s4Nes6ihxduFL0lLJjV1USq8U7mVar20nDNdiHxqjKZQ",
                            Gender = "Female",
                            Name = "Sophia L.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuAlm9ZnHv3XtmLsmCiE3BVixApLiZMOQQdxDL5p5s8XuWtINXFvePRxvb8cUJSMjPewgmI7KxhhZ4HDO05TkDeLrkXzZwDHElUSf-2Z3iqpnnGoW3cfdX8p-6rKBtb-iu8gMVI3-Xcauke-Ro6DNyQ7KtS6P84UoaY_Zrww-vicwSjDHtld1Z2SlPGVz7flzgID5kTv33hkULsiw7lwA4A6iRoZXLhlGcw_s4Nes6ihxduFL0lLJjV1USq8U7mVar20nDNdiHxqjKZQ"
                        },
                        new
                        {
                            Id = "chloe-r",
                            Category = "Fashion / High End",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuCzEae11HajK_A_XmyLtq50GnrZLqapqrXihXSrgQIOuj6vrFac-tjqr0hYtOQI24MuIDhf2MbozJtGWIiLHQ2tAOq-crvzaC-HZe-37hH7lf4nfEMyXpg0e6QBDsLys2BQurKITZB5BFbxn2aokABhYTEnUx7xZ7IZ2bIiC-1dDyWAA9PhqZpqcMiBmT1UbWHsqYUB9HMitkSCryuwTopPez7vRIi9ErUPChEjSLT7FR5y7Ng9sbsqD239FB_exp97HmaKkVWvB13n",
                            Gender = "Female",
                            Name = "Chloe R.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuCzEae11HajK_A_XmyLtq50GnrZLqapqrXihXSrgQIOuj6vrFac-tjqr0hYtOQI24MuIDhf2MbozJtGWIiLHQ2tAOq-crvzaC-HZe-37hH7lf4nfEMyXpg0e6QBDsLys2BQurKITZB5BFbxn2aokABhYTEnUx7xZ7IZ2bIiC-1dDyWAA9PhqZpqcMiBmT1UbWHsqYUB9HMitkSCryuwTopPez7vRIi9ErUPChEjSLT7FR5y7Ng9sbsqD239FB_exp97HmaKkVWvB13n"
                        },
                        new
                        {
                            Id = "david-k",
                            Category = "Casual / Everyday",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuD6DuXr3x3X79t_l1NkJMNLEHauz5fde4eTdt0b8KCYo0lhdNxzwjAg42EYaFZliu3eJP1z1y0Z5179XQHk_7yv8EM9dM0v9aWC3fEyMd-4I6RjcjPe3U8Jh0DV-e-avN-h-FzMqX1ku2RlMlEUd7fp-81ypo1JH0AkRZb-JbmId3fIIQufQY0psa1yueck3CglOpriLMSkbgwqXgrf9FviwNQ2pU0P2p28Ebffl9gCLMV4AD0xe1FyrNujVfgLplmMkdFXllF1Vlg8",
                            Gender = "Male",
                            Name = "David K.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuD6DuXr3x3X79t_l1NkJMNLEHauz5fde4eTdt0b8KCYo0lhdNxzwjAg42EYaFZliu3eJP1z1y0Z5179XQHk_7yv8EM9dM0v9aWC3fEyMd-4I6RjcjPe3U8Jh0DV-e-avN-h-FzMqX1ku2RlMlEUd7fp-81ypo1JH0AkRZb-JbmId3fIIQufQY0psa1yueck3CglOpriLMSkbgwqXgrf9FviwNQ2pU0P2p28Ebffl9gCLMV4AD0xe1FyrNujVfgLplmMkdFXllF1Vlg8"
                        },
                        new
                        {
                            Id = "maya-t",
                            Category = "Beauty / Close-up",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuDyg_lxWaOrDYttj5wgPZ5_m0ZaHr_5n9j2MMmJCFpuHNaoz5kO618aRaYDB-ic6EKjDZh8mOZXTgPgXlYRKAaIRMLo7Np5S4-t2TgCdA56aBOs5gkMmZHb9n7yvceRlGJ77BUUDdHqEWbvBmNs6DXYz1o2QAJURjYieclJRbmDf_Y_2QUjT2P32rnG1qwfkb6yzoX7WApYusE21mLRpQ-a_2Z1zHxYWIYj66Y2VkenKsk5Vz9LYl0UZjoAqvu_0nKnaQ_JbXI5zirT",
                            Gender = "Female",
                            Name = "Maya T.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuDyg_lxWaOrDYttj5wgPZ5_m0ZaHr_5n9j2MMmJCFpuHNaoz5kO618aRaYDB-ic6EKjDZh8mOZXTgPgXlYRKAaIRMLo7Np5S4-t2TgCdA56aBOs5gkMmZHb9n7yvceRlGJ77BUUDdHqEWbvBmNs6DXYz1o2QAJURjYieclJRbmDf_Y_2QUjT2P32rnG1qwfkb6yzoX7WApYusE21mLRpQ-a_2Z1zHxYWIYj66Y2VkenKsk5Vz9LYl0UZjoAqvu_0nKnaQ_JbXI5zirT"
                        },
                        new
                        {
                            Id = "zara-b",
                            Category = "Business / Formal",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuBk9i1u7KLFftSujohtoBwJuGdGFqUmTJ4s90JITB6TnZeTG4QcMZTgu3rF5LQvTQ-mMbwc_kHNl-yh1gc15SjUPQASoGvZfBc72HAkimL0FFCbmgRDcGOHkcKZ0bGtOe8mcrjfFY6kwGXy4mkO6iEnP-H8OyLw21CUW3eULNPm8T4fJRYEG7N5xHj7XQsyyoaZstq2oTBa_6vywGTk5X9E4RTjwMjU-NiNQkKQcUk8pyyqXoQCma9osZvM_UPDs2JPKSx87_ei4VjQ",
                            Gender = "Female",
                            Name = "Zara B.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuBk9i1u7KLFftSujohtoBwJuGdGFqUmTJ4s90JITB6TnZeTG4QcMZTgu3rF5LQvTQ-mMbwc_kHNl-yh1gc15SjUPQASoGvZfBc72HAkimL0FFCbmgRDcGOHkcKZ0bGtOe8mcrjfFY6kwGXy4mkO6iEnP-H8OyLw21CUW3eULNPm8T4fJRYEG7N5xHj7XQsyyoaZstq2oTBa_6vywGTk5X9E4RTjwMjU-NiNQkKQcUk8pyyqXoQCma9osZvM_UPDs2JPKSx87_ei4VjQ"
                        },
                        new
                        {
                            Id = "lily-a",
                            Category = "Artistic / Conceptual",
                            FullImagePath = "https://lh3.googleusercontent.com/aida-public/AB6AXuAtFeABsVMgskm3n1brapolfui2kgEyVi6Ve1O5N2NcVD_6-GJo9knrL1sk3sgwC7kvcumYtTqZkxDce8LhtxWBY-62Wp33k68sGgXqiYsj_q3O4tYZxYPawrImixcvc2a-tWQD93mxBnbBfm7Vt0sm3Muq_q3JbEcf-wEQUn5kSf3WahGfBz762URViP8xpM0F1hFL1KawI6bbGPNmyYgoHfOCttstNkd7tP_XpTIhlWY3yy-lR-oKQ7YDE4Ce4qgeGv95nzXbKow3",
                            Gender = "Female",
                            Name = "Lily A.",
                            ThumbnailPath = "https://lh3.googleusercontent.com/aida-public/AB6AXuAtFeABsVMgskm3n1brapolfui2kgEyVi6Ve1O5N2NcVD_6-GJo9knrL1sk3sgwC7kvcumYtTqZkxDce8LhtxWBY-62Wp33k68sGgXqiYsj_q3O4tYZxYPawrImixcvc2a-tWQD93mxBnbBfm7Vt0sm3Muq_q3JbEcf-wEQUn5kSf3WahGfBz762URViP8xpM0F1hFL1KawI6bbGPNmyYgoHfOCttstNkd7tP_XpTIhlWY3yy-lR-oKQ7YDE4Ce4qgeGv95nzXbKow3"
                        },
                        new
                        {
                            Id = "ai-generated",
                            Category = "AI",
                            FullImagePath = "/images/ai-placeholder.png",
                            Gender = "Unisex",
                            Name = "AI Generated",
                            ThumbnailPath = "/images/ai-placeholder.png"
                        });
                });

            modelBuilder.Entity("Giydir.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "İlk Projem",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Giydir.Core.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalAttributes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraAngle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lighting")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pose")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresModel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "upper_body",
                            Color = "white",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesyonel ve şık klasik beyaz gömlek",
                            IsActive = true,
                            Material = "cotton",
                            Name = "Klasik Beyaz Gömlek",
                            Pattern = "solid",
                            PromptTemplate = "professional white cotton classic shirt, clean white background, studio lighting, high quality fashion photography",
                            RequiresModel = false,
                            Style = "classic",
                            ThumbnailPath = "/images/templates/white-shirt.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Category = "upper_body",
                            Color = "black",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rahat ve modern spor tişört",
                            IsActive = true,
                            Material = "polyester",
                            Name = "Spor Tişört",
                            Pattern = "solid",
                            PromptTemplate = "modern black sporty t-shirt, athletic wear, clean background, professional product photography",
                            RequiresModel = false,
                            Style = "sporty",
                            ThumbnailPath = "/images/templates/sport-tshirt.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Category = "dresses",
                            Color = "navy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zarif ve şık kadın elbisesi",
                            IsActive = true,
                            Material = "silk",
                            Name = "Elegant Elbise",
                            Pattern = "solid",
                            PromptTemplate = "elegant navy blue silk dress, sophisticated fashion, clean background, luxury fashion photography",
                            RequiresModel = false,
                            Style = "elegant",
                            ThumbnailPath = "/images/templates/elegant-dress.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Category = "lower_body",
                            Color = "blue",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Klasik mavi kot pantolon",
                            IsActive = true,
                            Material = "denim",
                            Name = "Kot Pantolon",
                            Pattern = "denim",
                            PromptTemplate = "classic blue denim jeans, casual wear, clean background, professional fashion photography",
                            RequiresModel = false,
                            Style = "casual",
                            ThumbnailPath = "/images/templates/jeans.jpg"
                        });
                });

            modelBuilder.Entity("Giydir.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoutiqueName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 50,
                            Email = "demo@giydir.com",
                            Name = "Demo Kullanıcı",
                            PasswordHash = "demo123"
                        });
                });

            modelBuilder.Entity("Giydir.Core.Entities.GeneratedImage", b =>
                {
                    b.HasOne("Giydir.Core.Entities.ModelAsset", "ModelAsset")
                        .WithMany("GeneratedImages")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Giydir.Core.Entities.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelAsset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Giydir.Core.Entities.Project", b =>
                {
                    b.HasOne("Giydir.Core.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Giydir.Core.Entities.ModelAsset", b =>
                {
                    b.Navigation("GeneratedImages");
                });

            modelBuilder.Entity("Giydir.Core.Entities.Project", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Giydir.Core.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
